[package]
name = "cloudcover-cli"
version.workspace = true
edition.workspace = true
description = "Command-line interface for analyzing cloud SDK usage and generating permission policies"
license.workspace = true
repository.workspace = true

[[bin]]
name = "cloudcover"
path = "src/main.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/cloudcover-cli-v{ version }/cloudcover-cli-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install", "compile"]

[package.metadata.binstall.overrides.'cfg(windows)']
pkg-fmt = "zip"

[dependencies]
cloudcover-aws = { version = "0.1.2", path = "../clouds/cloudcover-aws" }
cloudcover-core = { version = "0.1.2", path = "../cloudcover-core" }
cloudcover-go = { version = "0.1.2", path = "../langs/cloudcover-go" }
cloudcover-terraform = { version = "0.1.2", path = "../langs/cloudcover-terraform" }
serde_json = "1.0"

[lints]
workspace = true
