[[package]]
name = "cloudcover"
version_group = "workspace"

[[package]]
name = "cloudcover-cli"
version_group = "workspace"

[[package]]
name = "cloudcover-core"
version_group = "workspace"

[[package]]
name = "cloudcover-site-data"
version_group = "workspace"

[[package]]
name = "cloudcover-aws"
version_group = "workspace"

[[package]]
name = "cloudcover-go"
version_group = "workspace"

[[package]]
name = "cloudcover-terraform"
version_group = "workspace"

[[package]]
name = "cloudcover-aws-sdk-go-v1"
version_group = "workspace"

[[package]]
name = "cloudcover-aws-sdk-go-v2"
version_group = "workspace"

[[package]]
name = "cloudcover-terraform-provider-aws"
version_group = "workspace"
