[package]
name = "cloudcover-terraform"
version.workspace = true
edition.workspace = true
description = "Terraform source analyzer for CloudCover"
license.workspace = true
repository.workspace = true

[dependencies]
cloudcover-core = { version = "0.1.4", path = "../../cloudcover-core" }
cloudcover-go = { version = "0.1.4", path = "../cloudcover-go" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
